/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.BodyTypeofCar;
import Model.CarModel;
import Model.IndividualCar;
import Model.StatusoftheCar;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author himani.walia
 */
public class AddCarInternalFrame extends javax.swing.JInternalFrame {

    AddCarInternalFrame previousframe;

    ArrayList<IndividualCar> indcar = new ArrayList<>();
    ArrayList<String> modelname = new ArrayList<>();
    ArrayList<CarModel> carmodel = new ArrayList<>();

    /**
     * Creates new form AddCarInternalFrame
     */
    public ArrayList<String> CarModelName() {

        for (CarModel cm : carmodel) {
            if (!modelname.contains(cm.getModel())) {
                modelname.add(cm.getModel());
            }
        }

        return modelname;

    }

    public void refreshcombobox() {
        modelname.clear(); 
        DefaultComboBoxModel cModel = new DefaultComboBoxModel(CarModelName().toArray());
        CarModelComboBox.setModel(cModel);
    }

    private boolean Checkfields() {
        if (RegisterationNumTextField.getText().isEmpty()
                || WOFDatePicker.getDate() == null
                || ColourTextField.getText().isEmpty()
                || YearofManufactureDatePicker.getDate() == null
                || DateRentedDatePicker.getDate() == null
                || DueDateDatePicker.getDate() == null
                || RentalAmountTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill out the fields");
        }
        return false;

    }

    /**
     * Creates new form CarDashboardInternalFrame
     */
    public AddCarInternalFrame() {
        initComponents();
        DefaultComboBoxModel typeofCar = new DefaultComboBoxModel(BodyTypeofCar.values());
        TypeofCarComboBox.setModel(typeofCar);
        DefaultComboBoxModel statusoftheCar = new DefaultComboBoxModel(StatusoftheCar.values());
        StatusofCarComboBox.setModel(statusoftheCar);
        carmodel.add(new CarModel(" Camry", "Toyota", "Petrol", 5, 25000));
        carmodel.add(new CarModel(" Accord", "Honda", "Hybrid", 5, 28000));
        carmodel.add(new CarModel(" Explorer", "Ford", "Gasoline", 5, 35000));
        carmodel.add(new CarModel(" Model 3", "Tesla", "Electric", 5, 50000));
        carmodel.add(new CarModel(" Silverado", "Chevrolet", "Diesel", 5, 40000));
        refreshcombobox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarModelComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        AddCarButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AddCarModelButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DueDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        DateRentedDatePicker = new org.jdesktop.swingx.JXDatePicker();
        RentalAmountTextField = new javax.swing.JTextField();
        WOFDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        YearofManufactureDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        TypeofCarComboBox = new javax.swing.JComboBox<>();
        RegisterationNumTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StatusofCarComboBox = new javax.swing.JComboBox<>();
        ColourTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(600, 388));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        CarModelComboBox.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("WOF(expiry date):");

        AddCarButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        AddCarButton.setText("ADD CAR ");
        AddCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Date Rented:");

        AddCarModelButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        AddCarModelButton.setText("ADD CAR MODEL");
        AddCarModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarModelButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Due Date :");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setText("Rental Amount:");

        DateRentedDatePicker.setToolTipText("");
        DateRentedDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateRentedDatePickerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setText("Type Of Car:");

        YearofManufactureDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearofManufactureDatePickerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Registeration Number:");

        RegisterationNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterationNumTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Status Of Car:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Colour:");

        StatusofCarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusofCarComboBoxActionPerformed(evt);
            }
        });

        ColourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setText("Car Model:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Year of Manufacture:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RentalAmountTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateRentedDatePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(YearofManufactureDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatusofCarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CarModelComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TypeofCarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DueDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WOFDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(RegisterationNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCarModelButton)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(AddCarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ColourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterationNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(DateRentedDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(YearofManufactureDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(RentalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusofCarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(CarModelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(WOFDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(DueDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeofCarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCarModelButton)
                .addGap(31, 31, 31)
                .addComponent(AddCarButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetFields() {
        // Reset or clear all input fields
        RegisterationNumTextField.setText("");
        WOFDatePicker.setDate(null);
        ColourTextField.setText("");
        YearofManufactureDatePicker.setDate(null);
        DateRentedDatePicker.setDate(null);
        DueDateDatePicker.setDate(null);
        RentalAmountTextField.setText("");
    }


    private void AddCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarButtonActionPerformed
        // TODO add your handling code here:
        if (!Checkfields()) {
            return;
        }
        String registerationNumber = RegisterationNumTextField.getText();
        Date wof = WOFDatePicker.getDate();
        String colour = ColourTextField.getText();
        Date yom = YearofManufactureDatePicker.getDate();
        Date daterented = DateRentedDatePicker.getDate();
        Date duedate = DueDateDatePicker.getDate();
        float rentalamount = Float.parseFloat(RentalAmountTextField.getText());

        indcar.add(new IndividualCar(registerationNumber, wof, colour, yom, daterented, duedate,
                rentalamount, BodyTypeofCar.SEDAN, StatusoftheCar.InShop, carmodel));

        if (Checkfields() == true) {
            JOptionPane.showMessageDialog(null, "Car added successfully!");
            resetFields();
        }

        AddCarInternalFrame frame = new AddCarInternalFrame();
        frame.previousframe = this;
        this.setVisible(false);
        frame.setVisible(true);


    }//GEN-LAST:event_AddCarButtonActionPerformed

    private void AddCarModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarModelButtonActionPerformed
        AddModel frame = new AddModel();
        frame.previousframe = this;
        this.setVisible(false);
        frame.setVisible(true);

    }//GEN-LAST:event_AddCarModelButtonActionPerformed

    private void DateRentedDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateRentedDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateRentedDatePickerActionPerformed

    private void YearofManufactureDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearofManufactureDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearofManufactureDatePickerActionPerformed

    private void StatusofCarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusofCarComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusofCarComboBoxActionPerformed

    private void ColourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColourTextFieldActionPerformed

    private void RegisterationNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterationNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterationNumTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarButton;
    private javax.swing.JButton AddCarModelButton;
    private javax.swing.JComboBox<String> CarModelComboBox;
    private javax.swing.JTextField ColourTextField;
    private org.jdesktop.swingx.JXDatePicker DateRentedDatePicker;
    private org.jdesktop.swingx.JXDatePicker DueDateDatePicker;
    private javax.swing.JTextField RegisterationNumTextField;
    private javax.swing.JTextField RentalAmountTextField;
    private javax.swing.JComboBox<String> StatusofCarComboBox;
    private javax.swing.JComboBox<String> TypeofCarComboBox;
    private org.jdesktop.swingx.JXDatePicker WOFDatePicker;
    private org.jdesktop.swingx.JXDatePicker YearofManufactureDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
