/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.CarModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author himani.walia
 */
public class AddModel extends javax.swing.JFrame {

    AddCarInternalFrame previousframe;
    String name;
    int seats;
    float engineSize;
    ArrayList<CarModel> carmodel = new ArrayList<>();

    /**
     * Creates new form AddModel
     */
    public AddModel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModelPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CarModelTextField = new javax.swing.JTextField();
        ManufacturerNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EngineSizeTextField = new javax.swing.JTextField();
        AddCarModelButton = new javax.swing.JButton();
        SeatsTextField = new javax.swing.JTextField();
        Fueltypetextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Model", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 48), new java.awt.Color(255, 51, 51))); // NOI18N
        ModelPanel.setOpaque(false);
        ModelPanel.setPreferredSize(new java.awt.Dimension(420, 230));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Model:");

        CarModelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarModelTextFieldActionPerformed(evt);
            }
        });

        ManufacturerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerNameTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Manufacturer Name:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Fuel Type:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("Seats:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setText("Engine Size:");

        EngineSizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineSizeTextFieldActionPerformed(evt);
            }
        });

        AddCarModelButton.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        AddCarModelButton.setText("ADD");
        AddCarModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarModelButtonActionPerformed(evt);
            }
        });

        SeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsTextFieldActionPerformed(evt);
            }
        });

        Fueltypetextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FueltypetextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModelPanelLayout = new javax.swing.GroupLayout(ModelPanel);
        ModelPanel.setLayout(ModelPanelLayout);
        ModelPanelLayout.setHorizontalGroup(
            ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ModelPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ModelPanelLayout.createSequentialGroup()
                            .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EngineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManufacturerNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Fueltypetextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCarModelButton)
                .addGap(167, 167, 167))
        );
        ModelPanelLayout.setVerticalGroup(
            ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CarModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ManufacturerNameTextField))
                .addGap(29, 29, 29)
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Fueltypetextfield))
                .addGap(28, 28, 28)
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(ModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EngineSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(AddCarModelButton)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ModelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddCarModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarModelButtonActionPerformed
        // TODO add your handling code here
        carmodel.add(new CarModel(" Camry", "Toyota", "Petrol", 5, 25000));
        carmodel.add(new CarModel(" Accord", "Honda", "Hybrid", 5, 28000));
        carmodel.add(new CarModel(" Explorer", "Ford", "Gasoline", 5, 35000));
        carmodel.add(new CarModel(" Model 3", "Tesla", "Electric", 5, 50000));
        carmodel.add(new CarModel(" Silverado", "Chevrolet", "Diesel", 5, 40000));

        if (CarModelTextField.getText().isEmpty() || ManufacturerNameTextField.getText().isEmpty()
                || SeatsTextField.getText().isEmpty() || Fueltypetextfield.getText().isEmpty()
                || EngineSizeTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            seats = Integer.parseInt(SeatsTextField.getText());
            engineSize = Float.parseFloat(EngineSizeTextField.getText());
            name = CarModelTextField.getText();
            for (CarModel existingcarmodel : previousframe.carmodel) {
                if (existingcarmodel.getModel().equalsIgnoreCase(name)) {
                    JOptionPane.showMessageDialog(this, "Model already exists");
                    return;
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Seats and engine size should be valid numbers ");
            return;
        }
        String manufacturer = ManufacturerNameTextField.getText();
        String fueltype = Fueltypetextfield.getText();
        CarModel c = new CarModel(name, manufacturer, fueltype, seats, engineSize);
        previousframe.carmodel.add(c);
        previousframe.refreshcombobox();
        previousframe.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_AddCarModelButtonActionPerformed

    private void ManufacturerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufacturerNameTextFieldActionPerformed

    private void FueltypetextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FueltypetextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FueltypetextfieldActionPerformed

    private void SeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsTextFieldActionPerformed

    private void EngineSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineSizeTextFieldActionPerformed

    private void CarModelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarModelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarModelTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarModelButton;
    private javax.swing.JTextField CarModelTextField;
    private javax.swing.JTextField EngineSizeTextField;
    private javax.swing.JTextField Fueltypetextfield;
    private javax.swing.JTextField ManufacturerNameTextField;
    private javax.swing.JPanel ModelPanel;
    private javax.swing.JTextField SeatsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
