/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Model.CarModel;
import Model.Customer;
import Model.Gender;
import Model.IndividualCar;
import Model.RentalRecord;
import static Model.StatusoftheCar.InShop;
import static Model.StatusoftheCar.RentedOut;
import static Model.StatusoftheCar.UnderManintance;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kashish Patel
 */
public class CarRentedByCustomerIFrame extends javax.swing.JInternalFrame {

    public ArrayList<Customer> customers = new ArrayList<>();
    public ArrayList<IndividualCar> indcar = new ArrayList<>();
    public ArrayList<CarModel> carmodel = new ArrayList<CarModel>();

//    
    public CarRentedByCustomerIFrame() throws ParseException {
        initComponents();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        Date date3 = dateFormat.parse("2025-08-14");
        Date date6 = dateFormat.parse("1887-03-08");
        Date date7 = dateFormat.parse("1897-06-27");
        Date date8 = dateFormat.parse("1977-03-11");
        Date date9 = dateFormat.parse("1997-06-27");
        Date date10 = dateFormat.parse("2026-09-30");
        Date date11 = dateFormat.parse("1997-08-24");
        Date date12 = dateFormat.parse("2025-11-05");
        Date date13 = dateFormat.parse("2026-08-14");
        Date date14 = dateFormat.parse("2026-08-20");


        customers.add(new Customer("0951843", "restriced", date3, "C01", "Bolton", Gender.MALE, date6, "123 Street Papakura Auckland", "0268739465"));
        customers.add(new Customer("220345", "Full License", date11, "C02", "Eden", Gender.MALE, date7, "123 Street Manurewa Auckland", "24674527472"));
        customers.add(new Customer("220355", "Restrict", date12, "C03", "Eve", Gender.FEMALE, date8, "123 Street Manukau Auckland", "24234567872"));
        customers.add(new Customer("220365", "Full License", date13, "C04", "Joshua", Gender.MALE, date9, "123 Street Otahuhu Auckland", "28653567832"));
        customers.add(new Customer("232342", "Full License", date14, "C05", "Kerry", Gender.FEMALE, date10, "123 Street Takanini Auckland", "3635326522"));

        
        indcar.add(new IndividualCar("ABC123", "Red", 12000, InShop));
        indcar.add(new IndividualCar("XYZ789", "Blue", 8000, RentedOut));
        indcar.add(new IndividualCar("LMN456", "Black", 3000, UnderManintance));
        indcar.add(new IndividualCar("PQR789", "White", 2000, RentedOut));

        carmodel.add(new CarModel(" Camry", "Toyota", "Petrol", 5, 25000));
        carmodel.add(new CarModel(" Accord", "Honda", "Hybrid", 5, 28000));
        carmodel.add(new CarModel(" Explorer", "Ford", "Gasoline", 5, 35000));
        carmodel.add(new CarModel(" Model 3", "Tesla", "Electric", 5, 50000));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Customeridtextfield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarTable = new javax.swing.JTable();

        jLabel1.setText("Customer ID:");

        searchbutton.setText("SEARCH");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        CarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Customer Phone", "Car Registeration No.", "Car Model", "Car Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CarTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Customeridtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(searchbutton)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Customeridtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
        String customerId = Customeridtextfield.getText();
        Customer cus = HomeForm.person.searchCustomerByID(customerId);

        if (cus == null) {
            JOptionPane.showMessageDialog(this, "Sorry, No Customer is found with ID: " + customerId);
        } else {

            DefaultTableModel model = (DefaultTableModel) CarTable.getModel();
            model.setRowCount(0);
            Object rows[] = new Object[5];
            for (Customer cu : customers) {
                if (cu.getPersonID().equals(customerId)) {

                    rows[0] = cu.getName();
                    rows[1] = cu.getPhone();

                    for (IndividualCar ic : indcar) {
                        rows[2] = ic.getRegisterationNumber();
                        rows[4] = ic.getStatus();
                        break;

                    }
                    for (CarModel cm : carmodel) {
                        rows[3] = cm.getModel();

                    }
                    model.addRow(rows);
                    break;
                }

    }//GEN-LAST:event_searchbuttonActionPerformed

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarTable;
    private javax.swing.JTextField Customeridtextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}
