/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;


/* * * * * * * * * 
 * @author Elisa *
 * @ID 220005803 * 
 * * * * * * * * */

public class EmployeeDashboardInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeeDashboardInternalFrame
     */
    public EmployeeDashboardInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeDesktopPane = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        CustomerDesktopPane1 = new javax.swing.JDesktopPane();
        ShowEmployeeButton = new javax.swing.JButton();
        UpdateEmployeeButton = new javax.swing.JButton();
        SearchEmployeeButton = new javax.swing.JButton();
        AddEmployeeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        EmployeeDesktopPane.setPreferredSize(new java.awt.Dimension(640, 510));

        javax.swing.GroupLayout CustomerDesktopPane1Layout = new javax.swing.GroupLayout(CustomerDesktopPane1);
        CustomerDesktopPane1.setLayout(CustomerDesktopPane1Layout);
        CustomerDesktopPane1Layout.setHorizontalGroup(
            CustomerDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        CustomerDesktopPane1Layout.setVerticalGroup(
            CustomerDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CustomerDesktopPane1)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(CustomerDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ShowEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ShowEmployeeButton.setForeground(new java.awt.Color(51, 102, 255));
        ShowEmployeeButton.setText("SHOW EMPLOYEE DETAILS");
        ShowEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowEmployeeButtonActionPerformed(evt);
            }
        });

        UpdateEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        UpdateEmployeeButton.setForeground(new java.awt.Color(51, 102, 255));
        UpdateEmployeeButton.setText("UPDATE EMPLOYEE DETAILS");
        UpdateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeButtonActionPerformed(evt);
            }
        });

        SearchEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        SearchEmployeeButton.setForeground(new java.awt.Color(51, 102, 255));
        SearchEmployeeButton.setText("SEARCH EMPLOYEE DETAILS");
        SearchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeeButtonActionPerformed(evt);
            }
        });

        AddEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        AddEmployeeButton.setForeground(new java.awt.Color(51, 102, 255));
        AddEmployeeButton.setText("ADD NEW EMPLOYEE");
        AddEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(51, 51, 255));
        backButton.setText("GO BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        EmployeeDesktopPane.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EmployeeDesktopPane.setLayer(ShowEmployeeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EmployeeDesktopPane.setLayer(UpdateEmployeeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EmployeeDesktopPane.setLayer(SearchEmployeeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EmployeeDesktopPane.setLayer(AddEmployeeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        EmployeeDesktopPane.setLayer(backButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EmployeeDesktopPaneLayout = new javax.swing.GroupLayout(EmployeeDesktopPane);
        EmployeeDesktopPane.setLayout(EmployeeDesktopPaneLayout);
        EmployeeDesktopPaneLayout.setHorizontalGroup(
            EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                .addGroup(EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UpdateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchEmployeeButton)
                    .addComponent(ShowEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                            .addGap(295, 295, 295)
                            .addComponent(backButton))
                        .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        EmployeeDesktopPaneLayout.setVerticalGroup(
            EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ShowEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(SearchEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(UpdateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(EmployeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeDesktopPaneLayout.createSequentialGroup()
                    .addGap(0, 249, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 248, Short.MAX_VALUE)))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Employee Management ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EmployeeDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowEmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeDesktopPane.removeAll();
        ShowEmployeeIFrame iframe = new ShowEmployeeIFrame();
        iframe.setVisible(true);
        EmployeeDesktopPane.add(iframe);

    }//GEN-LAST:event_ShowEmployeeButtonActionPerformed

    private void UpdateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeDesktopPane.removeAll();
        UpdateEmployeeIFrame iframe = new UpdateEmployeeIFrame();
        iframe.setVisible(true);
        EmployeeDesktopPane.add(iframe);
    }//GEN-LAST:event_UpdateEmployeeButtonActionPerformed

    private void SearchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeDesktopPane.removeAll();
        SearchEmployeeIFrame iframe = new SearchEmployeeIFrame();
        iframe.setVisible(true);
        EmployeeDesktopPane.add(iframe);
    }//GEN-LAST:event_SearchEmployeeButtonActionPerformed

    private void AddEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeButtonActionPerformed
        // TODO add your handling code here:
        EmployeeDesktopPane.removeAll();
        AddEmployeeIFrame iframe = new AddEmployeeIFrame();
        iframe.setVisible(true);
        EmployeeDesktopPane.add(iframe);

    }//GEN-LAST:event_AddEmployeeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        HomeForm form = new HomeForm();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeeButton;
    private javax.swing.JDesktopPane CustomerDesktopPane1;
    private javax.swing.JDesktopPane EmployeeDesktopPane;
    private javax.swing.JButton SearchEmployeeButton;
    private javax.swing.JButton ShowEmployeeButton;
    private javax.swing.JButton UpdateEmployeeButton;
    private javax.swing.JButton backButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
