/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import javax.swing.JOptionPane;
import Main.LoginForm;
import qualitycars.EmployeeAndCustomer;

/* * * * * * * * * 
 * @author Elisa *
 * @ID 220005803 * 
 * * * * * * * * */
public class HomeForm extends javax.swing.JFrame {

    public static EmployeeAndCustomer person;

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();

    }

    public HomeForm(String empName) {
        initComponents();

        employeeName.setText(empName.toUpperCase());
        JOptionPane.showMessageDialog(null, "Welcome, " + empName.toUpperCase() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        logOutPanel = new javax.swing.JPanel();
        profileLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CustomerManagementBtn1 = new javax.swing.JButton();
        CarRentalManagementBtn = new javax.swing.JButton();
        EmployeeManagementBtn = new javax.swing.JButton();
        StockManagementBtn1 = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainDesktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(51, 51, 51)));
        mainPanel.setForeground(new java.awt.Color(102, 102, 102));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(237, 246, 245));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        sidePanel.setPreferredSize(new java.awt.Dimension(130, 600));
        sidePanel.setRequestFocusEnabled(false);
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CarRental2.png"))); // NOI18N
        sidePanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 100));

        employeeName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeName.setForeground(new java.awt.Color(153, 0, 153));
        employeeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeName.setText("Employee Name");
        sidePanel.add(employeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 30));

        logOutPanel.setBackground(new java.awt.Color(153, 204, 255));
        logOutPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 255)));
        logOutPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutPanelMouseClicked(evt);
            }
        });

        profileLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        profileLabel2.setForeground(new java.awt.Color(102, 102, 102));
        profileLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel2.setText("LOG OUT");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leave_icon.png"))); // NOI18N

        javax.swing.GroupLayout logOutPanelLayout = new javax.swing.GroupLayout(logOutPanel);
        logOutPanel.setLayout(logOutPanelLayout);
        logOutPanelLayout.setHorizontalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOutPanelLayout.createSequentialGroup()
                .addGroup(logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logOutPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logOutPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logOutPanelLayout.setVerticalGroup(
            logOutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logOutPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidePanel.add(logOutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 110, 100));

        CustomerManagementBtn1.setBackground(new java.awt.Color(0, 153, 204));
        CustomerManagementBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerManagementBtn1.setForeground(new java.awt.Color(255, 255, 204));
        CustomerManagementBtn1.setText("Customer");
        CustomerManagementBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerManagementBtn1ActionPerformed(evt);
            }
        });
        sidePanel.add(CustomerManagementBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 50));

        CarRentalManagementBtn.setBackground(new java.awt.Color(0, 153, 204));
        CarRentalManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CarRentalManagementBtn.setForeground(new java.awt.Color(255, 255, 204));
        CarRentalManagementBtn.setText("Car Rental");
        CarRentalManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRentalManagementBtnActionPerformed(evt);
            }
        });
        sidePanel.add(CarRentalManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 130, 50));

        EmployeeManagementBtn.setBackground(new java.awt.Color(0, 153, 204));
        EmployeeManagementBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmployeeManagementBtn.setForeground(new java.awt.Color(255, 255, 204));
        EmployeeManagementBtn.setText("Employee");
        EmployeeManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeManagementBtnActionPerformed(evt);
            }
        });
        sidePanel.add(EmployeeManagementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 130, 50));

        StockManagementBtn1.setBackground(new java.awt.Color(0, 153, 204));
        StockManagementBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StockManagementBtn1.setForeground(new java.awt.Color(255, 255, 204));
        StockManagementBtn1.setText("Stock");
        StockManagementBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockManagementBtn1ActionPerformed(evt);
            }
        });
        sidePanel.add(StockManagementBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 130, 50));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 700));

        headerPanel.setBackground(new java.awt.Color(248, 250, 248));
        headerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        headerPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 90, 50));
        closeLabel.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car Rental Management System");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 490, 60));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2023-11-22 212541.png"))); // NOI18N

        MainDesktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainDesktopPaneLayout = new javax.swing.GroupLayout(MainDesktopPane);
        MainDesktopPane.setLayout(MainDesktopPaneLayout);
        MainDesktopPaneLayout.setHorizontalGroup(
            MainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainDesktopPaneLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainDesktopPaneLayout.setVerticalGroup(
            MainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(MainDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 860, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void logOutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutPanelMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutPanelMouseClicked

    private void CustomerManagementBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerManagementBtn1ActionPerformed
        // TODO add your handling code here:M

        MainDesktopPane.removeAll();
        CustomerDashboardInternalFrame iframe = new CustomerDashboardInternalFrame();
        iframe.setVisible(true);
        MainDesktopPane.add(iframe);

    }//GEN-LAST:event_CustomerManagementBtn1ActionPerformed

    private void StockManagementBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockManagementBtn1ActionPerformed
        // TODO add your handling code here:

        MainDesktopPane.removeAll();
        StockDashboardInternalFrame iframe = new StockDashboardInternalFrame();
        iframe.setVisible(true);
        MainDesktopPane.add(iframe);
    }//GEN-LAST:event_StockManagementBtn1ActionPerformed

    private void CarRentalManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRentalManagementBtnActionPerformed
        // TODO add your handling code here:
        MainDesktopPane.removeAll();
        RentalDashboardInternalFrame iframe = new RentalDashboardInternalFrame();
        iframe.setVisible(true);
        MainDesktopPane.add(iframe);

    }//GEN-LAST:event_CarRentalManagementBtnActionPerformed

    private void EmployeeManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeManagementBtnActionPerformed
        // TODO add your handling code here:
        MainDesktopPane.removeAll();
        EmployeeDashboardInternalFrame iframe = new EmployeeDashboardInternalFrame();
        iframe.setVisible(true);
        MainDesktopPane.add(iframe);

    }//GEN-LAST:event_EmployeeManagementBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarRentalManagementBtn;
    private javax.swing.JButton CustomerManagementBtn1;
    private javax.swing.JButton EmployeeManagementBtn;
    private javax.swing.JDesktopPane MainDesktopPane;
    private javax.swing.JButton StockManagementBtn1;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel employeeName;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel logOutPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel profileLabel2;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
