/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author himani.walia
 */
public class RentalDashboardInternalFrame extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form RentalDashboardInternalFrame
     */
    public RentalDashboardInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CarRentedByCustomerButton = new javax.swing.JButton();
        InformationDesktopPane = new javax.swing.JDesktopPane();
        RentCarButton = new javax.swing.JButton();
        ReturnCarButton = new javax.swing.JButton();
        CarRentedByDatesButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 510));

        CarRentedByCustomerButton.setText("CARS RENTED BY CUSTOMER");
        CarRentedByCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRentedByCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformationDesktopPaneLayout = new javax.swing.GroupLayout(InformationDesktopPane);
        InformationDesktopPane.setLayout(InformationDesktopPaneLayout);
        InformationDesktopPaneLayout.setHorizontalGroup(
            InformationDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        InformationDesktopPaneLayout.setVerticalGroup(
            InformationDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        RentCarButton.setText("RENT A CAR");
        RentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentCarButtonActionPerformed(evt);
            }
        });

        ReturnCarButton.setText("RETURN CAR");
        ReturnCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCarButtonActionPerformed(evt);
            }
        });

        CarRentedByDatesButton.setText("CARS RENTED BY SELECTED DATES");
        CarRentedByDatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarRentedByDatesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CarRentedByCustomerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                        .addComponent(CarRentedByDatesButton)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InformationDesktopPane)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(RentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnCarButton)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformationDesktopPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnCarButton)
                    .addComponent(RentCarButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarRentedByCustomerButton)
                    .addComponent(CarRentedByDatesButton))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarRentedByCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRentedByCustomerButtonActionPerformed
        try {
            // TODO add your handling code here:
            InformationDesktopPane.removeAll();
            CarRentedByCustomerIFrame iframe = new CarRentedByCustomerIFrame();
            iframe.setVisible(true);
            InformationDesktopPane.add(iframe);
        } catch (ParseException ex) {
            Logger.getLogger(RentalDashboardInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_CarRentedByCustomerButtonActionPerformed

    private void RentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentCarButtonActionPerformed
        // TODO add your handling code here:
        InformationDesktopPane.removeAll();
        RentCartoCustomerInternalFrame iframe = new RentCartoCustomerInternalFrame();
        iframe.setVisible(true);
        InformationDesktopPane.add(iframe);
    }//GEN-LAST:event_RentCarButtonActionPerformed

    private void ReturnCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCarButtonActionPerformed
        // TODO add your handling code here:
        InformationDesktopPane.removeAll();
        ReturnCarInternalFrame iframe = new ReturnCarInternalFrame();
        iframe.setVisible(true);
        InformationDesktopPane.add(iframe);
        
    }//GEN-LAST:event_ReturnCarButtonActionPerformed

    private void CarRentedByDatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarRentedByDatesButtonActionPerformed
        // TODO add your handling code here:
        InformationDesktopPane.removeAll();
        RentedCarsBySelectedDates iframe = new RentedCarsBySelectedDates();
        iframe.setVisible(true);
        InformationDesktopPane.add(iframe);
    }//GEN-LAST:event_CarRentedByDatesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarRentedByCustomerButton;
    private javax.swing.JButton CarRentedByDatesButton;
    private javax.swing.JDesktopPane InformationDesktopPane;
    private javax.swing.JButton RentCarButton;
    private javax.swing.JButton ReturnCarButton;
    // End of variables declaration//GEN-END:variables
}
