/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import qualitycars.StockManagementSystem;

/**
 *
 * @author himani.walia
 */
public class StockDashboardInternalFrame extends javax.swing.JInternalFrame {
    public static StockManagementSystem stockmanagementsystem ;

    /**
     * Creates new form StockDashboardInternalFrame
     */
    public StockDashboardInternalFrame() {
        stockmanagementsystem = new StockManagementSystem();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StockDesktopPane = new javax.swing.JDesktopPane();
        AddCarButton = new javax.swing.JButton();
        SearchCarButton = new javax.swing.JButton();
        UpdatelCarButton = new javax.swing.JButton();
        RentalCarButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setClosable(true);

        StockDesktopPane.setPreferredSize(new java.awt.Dimension(860, 630));

        AddCarButton.setBackground(new java.awt.Color(153, 204, 255));
        AddCarButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        AddCarButton.setForeground(new java.awt.Color(0, 51, 255));
        AddCarButton.setText("ADD CAR");
        AddCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarButtonActionPerformed(evt);
            }
        });

        SearchCarButton.setBackground(new java.awt.Color(153, 204, 255));
        SearchCarButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        SearchCarButton.setForeground(new java.awt.Color(0, 51, 255));
        SearchCarButton.setText("SEARCH CAR ");
        SearchCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCarButtonActionPerformed(evt);
            }
        });

        UpdatelCarButton.setBackground(new java.awt.Color(153, 204, 255));
        UpdatelCarButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        UpdatelCarButton.setForeground(new java.awt.Color(0, 51, 255));
        UpdatelCarButton.setText("UPDATE CAR INFORMATION");
        UpdatelCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatelCarButtonActionPerformed(evt);
            }
        });

        RentalCarButton1.setBackground(new java.awt.Color(153, 204, 255));
        RentalCarButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        RentalCarButton1.setForeground(new java.awt.Color(0, 51, 255));
        RentalCarButton1.setText("RENTAL CARS");
        RentalCarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentalCarButton1ActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(153, 204, 255));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(51, 51, 255));
        backButton.setText("GO BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        StockDesktopPane.setLayer(AddCarButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StockDesktopPane.setLayer(SearchCarButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StockDesktopPane.setLayer(UpdatelCarButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StockDesktopPane.setLayer(RentalCarButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        StockDesktopPane.setLayer(backButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout StockDesktopPaneLayout = new javax.swing.GroupLayout(StockDesktopPane);
        StockDesktopPane.setLayout(StockDesktopPaneLayout);
        StockDesktopPaneLayout.setHorizontalGroup(
            StockDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockDesktopPaneLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(StockDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(SearchCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentalCarButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdatelCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(AddCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        StockDesktopPaneLayout.setVerticalGroup(
            StockDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockDesktopPaneLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(SearchCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(RentalCarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(UpdatelCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(AddCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StockDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StockDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        StockDesktopPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarButtonActionPerformed
        // TODO add your handling code here:
         StockDesktopPane.removeAll();
        AddCarInternalFrame iframe = new AddCarInternalFrame();
        iframe.setVisible(true);
        StockDesktopPane.add(iframe);
        
        
        
    }//GEN-LAST:event_AddCarButtonActionPerformed

    private void SearchCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCarButtonActionPerformed
        // TODO add your handling code here:
        StockDesktopPane.removeAll();
        SearchCarInternalFrame iframe = new SearchCarInternalFrame();
        iframe.setVisible(true);
        StockDesktopPane.add(iframe);
    }//GEN-LAST:event_SearchCarButtonActionPerformed

    private void UpdatelCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatelCarButtonActionPerformed
        // TODO add your handling code here:
        StockDesktopPane.removeAll();
        UpdateCarInternalFrame iframe = new UpdateCarInternalFrame();
        iframe.setVisible(true);
        StockDesktopPane.add(iframe);
        
    }//GEN-LAST:event_UpdatelCarButtonActionPerformed

    private void RentalCarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentalCarButton1ActionPerformed
        // TODO add your handling code here:
        StockDesktopPane.removeAll();
        RentalCarInternalFrame iframe = new RentalCarInternalFrame();
        iframe.setVisible(true);
        StockDesktopPane.add(iframe);
    }//GEN-LAST:event_RentalCarButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        HomeForm form = new HomeForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarButton;
    private javax.swing.JButton RentalCarButton1;
    private javax.swing.JButton SearchCarButton;
    private javax.swing.JDesktopPane StockDesktopPane;
    private javax.swing.JButton UpdatelCarButton;
    private javax.swing.JButton backButton;
    // End of variables declaration//GEN-END:variables
}
